admin_research_assistant_task:
  description: >
    Please conduct a comprehensive analysis of the bank account reports and available investments in the real estate business in Florida on today's date.  
    The analysis should include the following key points: 
    Bank report key points: Provide the opening balance, every transaction, and closing balance in the report.
    Business Overview: Briefly describe each business model found for investment, its services, and its target market.
    Risk Factors: Identify and discuss the major risk factors for investing in that business.
    Competitive Landscape: Discuss the competitive position in the industry and how it compares to its major competitors.
    Future Outlook: Based on the information and your analysis, provide a brief outlook on future performance.
    Please ensure that all information is sourced from authetic sources and the analysis is unbiased and factual.
  expected_output: >
    The analysis report in bullet points is in accordance with the given key points.

chief_finance_officer_task:
  description: >
    Using the insights provided by the Admin Research Assistant, think through deeply the future implications of the points that are made. 
    Consider the following questions as you craft your response:
    What are our plans for the investments mentioned in the Admin Research Assistant report?
    How much money do we need to invest given all options including key points for each?
    Is there sufficient money to invest in a plan that has been approved by the CEO?
    What are the methods to obtain a loan for more money?
    Provide a detailed analysis of each of the questions. To take further steps, it is important to obtain approval for each question from the CEO.
    For an investment loan, do an internet search for the best available loan plan. 
  expected_output: >
    A report that analyzes and provides deeper insights, including actual human capabilities.
chief_excutive_officer_task:
  description: >
    Using the insights provided by the Admin Research Assistant and Chief Finance Officer, please craft an expert-styled decision 
    that is targeted toward the investor community. It is important to consider the long-term consequences of the insights mentioned.  
    
    Ensure that you have the authority to be the CEO of the company and approve or request changes to the guidelines directed by the Chief Finance Officer.
  expected_output: >
    Expert-styled decision-making like a real human in coordination with your Admin Research Assistant and Chief Finance Officer.