admin_assistant_manager_task:
  description: >
    please conduct a comprehensive analysis on bank account report and avialble investments in Real estate business in Florida on today date. 
    The analysis should include the following key points:
    
    Bank Report Key Points: Give the opening blance, every transactions and closing balance in report.

    Business Overview: Briefly describe each business model found for investment, its services, and its target market.
    
    Risk Factors: Identify and discuss the major risk factors that for for innesting in that business.
        
    Competitive Landscape: Discuss competitive position in industry and how it compares to its major competitors.
    
    Future Outlook: Based on the information and your analysis, provide a brief outlook on future performance.
    
    Please ensure that all information is sourced from authetic sources and the analysis is unbiased and factual.
  expected_output: >
    Full analysis report in bullet points fulfill all given key points.

chief_finance_officer_task:
  description: >
    Using the insights provided by the Assistant Admin Manager, think through deeply the future implications of the points that are made. 
    Consider the following questions as you craft your response:
    
    What is our plan regarding the investments  mentioned in the Assistant Admin Manager report?
    
    How much money do we need to investment give all options including key points for each?
    
    Do we have enough money to invest in plan approved with CEO?
    
    What is the strategy to get a loan for more money?
    
    Provide a detailed analysis on each of the questions. And also get approved each questions with by the CEO to take furthre steps. If required 
    loan for investment do internet search for best avialble loan plan. 
  expected_output: >
    Analysis report with deeper insights like a real human capabilities.

chief_excutive_officer_task:
  description: >
    Using the insights provided by the Assitant Admin Manager and Chief Finance Officer, please craft an expertly
    styled decision that is targeted towards the investor community. Make sure to also include the long-term implications
    of the insights that are mentioned.  
    
    Please ensure that you are the CEO of the company you may approved the Chief Finnace Officer decision or also ask for chnages with
    directed guidelines.
  expected_output: >
    A expertly styled decsion making to take decision for the done  by your co-worker, Admin Assistant Manager and Chief Finance Officer.
