 invoices.netze.preparation:
  description: >
    Create invoices for clients. 
    Update dates in the Google Sheets template {Rechnung - Maximilian Garmatsch}.
    For cell {I8}, set {the sixth digit to the number of upcoming month}.
    for cell {I10}, set to {first of the month}.
    for cell {I11}, set to {end of the month}.
    for cell {D16}, set {the month to the current month}.
    Access the Google Sheet {Timesheet - Maximilian Garmatsch - Netze BW 2023/2024} and copy the cell {C52}
    and paste in {Rechnung} template in cell {E16}.
    save the updated document as a PDF.
    Create a Google Drive folder in folder "Netze BW / NOW" and name it "2024-[current month]"
    Upload the PDF to the Google Drive folder.
    Access email account {maximilian.garmatsch@gmail.com}
    Draft an email with details:
    Subject: "Rechnung [MONTH in GERMAN] 2024"
    Body: "
    Sehr geerhte Damen und Herren,
    anbei ist mein Timesheet und die Rechnung für [MONTH] 2024.
    Das standard Zahlungsziel ist ok.
    Über eine kurze Bestätigung wäre ich sehr dankbar, Anpassungen kann ich sofort nachreichen. Vielen Dank.
    "
    Find the signed Timesheet in the emails named "Timesheet - Maximilian Garmatsch - Netze BW - [Month] 2024 - Signed"
    Add  Invoice
    Add Recipient "e-rechnung@solcom.de"
    Add CC "A.Braun@solcom.de"
  expected_output: >
    A PDF invoice in a Google Drive folder, and a draft of the email with the right details.

invoices.team-members.preparation: >
 description: >
    Access Google sheet {Team Invoices}.
    Locate sheet {Query}, Copy the first member name from column {A}, and paste in sheet {Invoice Template} in cell {C2}.
    The team members' data will appear automatically.
    Update the date in sheet {Query} in cell {A10} by adding 2 weeks to it.
    Navigate to {Apps Script} and run the scenario.
    Repeat the process for the next member name in column {A} in sheet {Query}, except for updating the date step.
    Do this for all team members one by one until the end.
 
 expected_output: >
    PDF invoices are saved in the respective team members' folders in Google Drive.

bill_payments: >
 description: >
    Log into {Telekom.hu}
    In section {Bills} click on {Payment}
    Click on the default card
    After the message " You don't have any pending invoices " Appear, Locate " Details " and click on it for the first invoice.
    Click on " Download PDF invoice"
    Repeat the locating for " details " for the second invoice.
    Rename the first invoice {Telekom Home [Date]} and the second invoice {Telekom mobile [Date]}.
    log into {ClickUp}, and Upload the invoices in the comments of the task {Telekom.hu: Pay & Download Invoices} 
    If both invoices sum is over {8000}, write a comment " it's over 8000+ this month", and mention {Max}.

 expected_output: >
    Invoices are saved in the comments of the task.
